spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JC_GWG?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: jc
    password: jc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null

game:
  difficultyLevelChanger: 6